// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Models.Entities;

//public partial class Detail
//{
//    public int BusinessEntityId { get; set; }

//    public string Details { get; set; }

//    public byte[] Version { get; set; }
//}