// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Models.Entities;

public partial class Enmascarado
{
    public int ClienteId { get; set; }

    public string NombreCompleto { get; set; }

    public string CorreoElectronico { get; set; }

    public string TarjetaCredito { get; set; }

    public int ScoreRiesgo { get; set; }

    public DateTime FechaPorDedecto { get; set; }

    public DateTime FechaCumpleaños { get; set; }
}