// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Models.Entities;

public partial class Notificacione
{
    public int Id { get; set; }

    public string Mensaje { get; set; }

    public string Remitente { get; set; }

    public bool Leido { get; set; }

    public string Propietario { get; set; }

    public byte[] Version { get; set; }
}