// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Curso.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Curso.Models.Infraestructure
{
    public partial class AWContext
    {
        private IAWContextProcedures _procedures;

        public virtual IAWContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AWContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAWContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AWContextProcedures : IAWContextProcedures
    {
        private readonly AWContext _context;

        public AWContextProcedures(AWContext context)
        {
            _context = context;
        }

        public virtual async Task<List<uspSearchCandidateResumesResult>> uspSearchCandidateResumesAsync(string searchString, bool? useInflectional, bool? useThesaurus, int? language, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "searchString",
                    Size = 1000,
                    Value = searchString ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "useInflectional",
                    Value = useInflectional ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "useThesaurus",
                    Value = useThesaurus ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "language",
                    Value = language ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<uspSearchCandidateResumesResult>("EXEC @returnValue = [dbo].[uspSearchCandidateResumes] @searchString = @searchString, @useInflectional = @useInflectional, @useThesaurus = @useThesaurus, @language = @language", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
