// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Curso.Models.Entities;
using Curso.Tools;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Curso.Models.Infraestructure;

public partial class AWContext : DbContext {

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder) {
        modelBuilder.Entity<Detail>(entity => {
            //entity.HasKey(e => e.BusinessEntityId).HasName("PK__Details__88984337C3F38869");

            //entity.ToTable("Details", "Person");

            //entity.Property(e => e.BusinessEntityId)
            //    .ValueGeneratedNever()
            //    .HasColumnName("BusinessEntityID");
            //entity.Property(e => e.Version)
            //    .IsRequired()
            //    .IsRowVersion()
            //    .IsConcurrencyToken()
            //    .HasColumnName("version");
            entity.ComplexProperty(e => e.Details, rootBuilder => {
                rootBuilder.ToJson("Details");
                rootBuilder.Property(rc => rc.EmailAddresses)
                    .IsRequired();
            });
            //entity.OwnsOne(
            //    e => e.Details,
            //    c => {
            //        c.Property(p => p.ContactType).HasColumnName("ContactType");
            //        c.OwnsMany(p => p.Addresses, a => {
            //            a.Property(a => a.Type).IsRequired();
            //            a.Property(a => a.AddressLine1).IsRequired();
            //            a.Property(a => a.AddressLine2);
            //            a.Property(a => a.City).IsRequired();
            //            a.Property(a => a.PostalCode).IsRequired();
            //            a.Property(a => a.StateProvince).IsRequired();
            //        });
            //        c.OwnsMany(p => p.PhoneNumbers, t => {
            //            t.Property(a => a.Type).IsRequired();
            //            t.Property(a => a.Number).IsRequired();
            //        });
            //        //c.OwnsMany(p => p.EmailAddresses);
            //    });
        });
    }

    private void validateEntities() {
        if(ChangeTracker.Entries()
            .Where(e => (e.State == EntityState.Added || e.State == EntityState.Modified) && e.Entity.IsInvalid())
            .Any())
            throw new ValidationException("Error en la validación de las entidades");
    }
    public override int SaveChanges() {
        validateEntities();
        return base.SaveChanges();
    }
    public override int SaveChanges(bool acceptAllChangesOnSuccess) {
        validateEntities();
        return base.SaveChanges(acceptAllChangesOnSuccess);
    }
    public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default) {
        validateEntities();
        return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
    }
}