// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Curso.Models.Entities;

public partial class Detail {
    public int BusinessEntityId { get; set; }

    //public string Details { get; set; }
    public DetailsJson Details { get; set; }
    public byte[] Version { get; set; }
}

public class DetailsJson {
    public string ContactType { get; set; }
    public List<AddressJson> Addresses { get; set; }
    public List<PhoneNumberJson> PhoneNumbers { get; set; }
    public List<string> EmailAddresses { get; set; }
}

public class AddressJson {
    public string Type { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string City { get; set; }
    public string PostalCode { get; set; }
    public string StateProvince { get; set; }
}

public class PhoneNumberJson {
    public string Type { get; set; }
    public string Number { get; set; }
}
