// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demos.Models.Domain;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Demos.Models.Infraestructure
{
    public partial class AWContext
    {
        private IAWContextProcedures _procedures;

        public virtual IAWContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AWContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAWContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AWContextProcedures : IAWContextProcedures
    {
        private readonly AWContext _context;

        public AWContextProcedures(AWContext context)
        {
            _context = context;
        }

        public virtual async Task<List<uspGetManagerEmployeesResult>> uspGetManagerEmployeesAsync(int? businessEntityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BusinessEntityID",
                    Value = businessEntityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<uspGetManagerEmployeesResult>("EXEC @returnValue = [dbo].[uspGetManagerEmployees] @BusinessEntityID = @BusinessEntityID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
