// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Demos.Models.Domain;

namespace Demos.Models.Infraestructure
{
    public partial class AWContext
    {

        [DbFunction("ufnSalesOrderHeaderChanges", "dbo")]
        public IQueryable<ufnSalesOrderHeaderChangesResult> ufnSalesOrderHeaderChanges(long? previusVersion)
        {
            return FromExpression(() => ufnSalesOrderHeaderChanges(previusVersion));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ufnSalesOrderHeaderChangesResult>().HasNoKey();
        }
    }
}
