// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Demos.Models.Domain;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Demos.Models.Infraestructure
{
    public partial interface IAWContextProcedures
    {
        Task<List<uspGetManagerEmployeesResult>> uspGetManagerEmployeesAsync(int? businessEntityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
